# First is basic bot configuration. Properties needed to connect the bot
bot:
  # The username with which the bot connects
  user: bot
  # The password used for connection
  password: secret
  # The bot self-identifies with this name
  name: pwr-bot
  # Rooms to join when the bot connects
  default-rooms:
    - pwr-bot-test
    - some-other-room
    - secret-room
  # The host-URL of the rocket chat server
  host: rocket.chat
# Logging configuration. Values listed here are defaults.
logging:
  error: true
  warn: true
  info: true
  log: true
  debug: false
install-script: yarn add {0} # npm install --save {0} if you are running npm and not yarn
commands:
  # This is the location for all custom commands. Custom commands dont have access to the bot itself
  custom-location: /commands
  # All commands crucial to the bots operation. System commands get the manager injected, granting them access to the manager
  system-location: /system-commands
  # Commands that are supposed to be ignored by the bot. Name is mandatory for this to work
  ignored:
    - who-knows
    - sample
# From here, it's command specific configuration
# If your command needs some for of configuration, simply leave it here
# As soon as your command gets picket up by the manager, the manager will ask for the commands name. In case of the help command, its help
# The manager will then provide everything that belongs to command-config.help as JS object to the commad.
command-config:
  self-update:
    authorized-users:
      -john.doe
  help:
    keywords:
      - help
      - hilfe
      - l'aide
